#!/usr/bin/env python3
"""Rebuild the published Sim 2.5 browser page from the public simulation outputs.

This is the public, self-contained counterpart of the project's private page builder. It
does not run SWMM. It converts the saved grid under simulation_src/results/sim25/grid into
the static JavaScript payload used by the browser and reconstructs the network geometry
from the exact public ArcGIS snapshot under simulation_src/data/raw.

The already-public HTML, JavaScript UI, and narrative content in simulation25 are treated
as page templates. The numerical catchment.js and growth.js files are regenerated.

Examples:
    python tools/build_sim25_web.py
    python tools/build_sim25_web.py --out reproduced_simulation25 --check
"""
import argparse
import filecmp
import glob
import io
import json
import os
import shutil
import sys


HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SIM = os.path.join(ROOT, "simulation_src")
GRID = os.path.join(SIM, "results", "sim25", "grid")
TEMPLATE = os.path.join(ROOT, "simulation25")
sys.path.insert(0, SIM)

PAGE_FILES = ["index.html", "growth_ui.js", "growth_3d.js"]
MAX_SENSORS = 10
WEATHER_LABEL = {0.0: "Dry", 0.11: "Design wet", 0.25: "Beyond design", 0.40: "Severe"}
WEATHER_NOTE = {
    0.0: "Sewage only, no infiltration: a genuinely dry day.",
    0.11: "Infiltration at the level that just meets the utility's own design rating for "
          "these pipes.",
    0.25: "1.7 times the design envelope: an old network on a wet day.",
    0.40: "2.4 times the design envelope: a heavy wet period.",
}
RULES = [
    ("alarm", "150 mm alarm", "Seen when the depth newly passes 150 mm above the pipe floor "
     "(the low alarm used in a real deployment)."),
    ("r10", "Rise 10 mm", "Seen when the depth rises at least 10 mm over that manhole's "
     "own level before the growth."),
    ("r25", "Rise 25 mm", "Seen when the depth rises at least 25 mm over that manhole's "
     "own level before the growth."),
    ("r50", "Rise 50 mm", "Seen when the depth rises at least 50 mm over that manhole's "
     "own level before the growth."),
]


def write_js(path, varname, payload):
    body = json.dumps(payload, separators=(",", ":"), allow_nan=False)
    text = (
        "// Generated by tools/build_sim25_web.py - do not edit by hand.\n"
        "// EPA SWMM output, quantised and base64 packed. The physics is SWMM's;\n"
        "// this file is only its saved answer.\n"
        f"window.{varname} = {body};\n"
    )
    io.open(path, "w", encoding="utf-8", newline="\n").write(text)
    return len(text.encode("utf-8"))


def case_label(case):
    label = WEATHER_LABEL.get(round(case["ii"], 2), f"I&I {case['ii']}")
    extra = []
    if case["pf"] == "harmon":
        extra.append("Harmon peaking")
    if case["age"] == "weighted":
        extra.append("age-weighted I&I")
    if case["bfac"] != 1.0:
        extra.append(f"outside inflow x{case['bfac']:g}")
    return label + (" + " + ", ".join(extra) if extra else "")


def placement(per_case, n_chambers, k_max=MAX_SENSORS):
    """Choose nested 1-to-k sensor sets and derive the single-sensor heatmap."""
    cases = [[set(tips) for tips in sets if tips] for sets in per_case]
    cases = [case for case in cases if case]
    alone = []
    for manhole in range(n_chambers):
        fractions = [sum(1 for tips in case if manhole in tips) / len(case) for case in cases]
        alone.append(fractions)
    heat = {
        "worst": [round(min(fractions), 4) for fractions in alone],
        "mean": [round(sum(fractions) / len(fractions), 4) for fractions in alone],
    }

    def cover(chosen):
        return [sum(1 for tips in case if tips & chosen) / len(case) for case in cases]

    result = {}
    for objective in ("mean", "worst"):
        chosen, order, worst, mean = set(), [], [], []
        for _ in range(k_max):
            best, best_key = None, None
            for manhole in range(n_chambers):
                if manhole in chosen:
                    continue
                fractions = cover(chosen | {manhole})
                if objective == "mean":
                    key = (sum(fractions) / len(fractions), min(fractions))
                else:
                    key = (min(fractions), sum(fractions) / len(fractions))
                if best_key is None or key > best_key:
                    best, best_key = manhole, key
            chosen.add(best)
            order.append(best)
            fractions = cover(chosen)
            worst.append(round(min(fractions), 4))
            mean.append(round(sum(fractions) / len(fractions), 4))
        result[objective] = {"order": order, "worst": worst, "mean": mean}
    return heat, result


def catchment_geometry(outlet):
    """Build drawing geometry from the same Catchment object supplied to SWMM."""
    from network import Network
    import catchment

    network = Network()
    model = catchment.Catchment(network, outlet)
    xs = [point[0] for link in model.links for point in link.line]
    ys = [point[1] for link in model.links for point in link.line]
    zs = [value for link in model.links for value in (link.inv_up, link.inv_down)]
    ox, oy, oz = min(xs), min(ys), min(zs)

    px, py, ptr, zu, zd, dia, up, down = [], [], [], [], [], [], [], []
    names = list(model.nodes)
    index = {name: i for i, name in enumerate(names)}
    for link in model.links:
        ptr.append(len(px))
        for x, y in link.line:
            px.append(int(round((x - ox) * 10)))
            py.append(int(round((y - oy) * 10)))
        zu.append(int(round((link.inv_up - oz) * 100)))
        zd.append(int(round((link.inv_down - oz) * 100)))
        dia.append(int(round(link.dia * 1000)))
        up.append(index[link.up])
        down.append(index[link.down])
    ptr.append(len(px))

    nodes = []
    for name in names:
        node = model.nodes[name]
        nodes.append({
            "name": name,
            "kind": node.kind,
            "x": int(round((node.x - ox) * 10)),
            "y": int(round((node.y - oy) * 10)),
            "inv": int(round((node.invert - oz) * 100)),
            "depth": round(node.max_depth, 3),
            "mh": node.manhole_id,
            "dw": model.dwellings.get(name, 0),
        })

    study_assets = {pipe.asset_id for pipe in model.pipes if pipe.role == "study"}
    in_model = {i for i, pipe in enumerate(network.pipes) if pipe.asset_id in study_assets}
    hx, hy, hz, hn = [], [], [], []
    for x, y, pipe_id in getattr(network, "connections", []):
        if pipe_id in in_model:
            pipe = network.pipes[pipe_id]
            hx.append(int(round((x - ox) * 10)))
            hy.append(int(round((y - oy) * 10)))
            hz.append(int(round(((pipe.inv_up + pipe.inv_down) / 2 - oz) * 100)))
            hn.append(index[model.node_of[pipe.up]])

    outlet_name = model.node_of.get(outlet)
    return {
        "outletName": outlet_name,
        "outletManhole": model.nodes[outlet_name].manhole_id if outlet_name else None,
        "ox": round(ox, 2), "oy": round(oy, 2), "oz": round(oz, 3),
        "px": px, "py": py, "ptr": ptr, "zu": zu, "zd": zd, "dia": dia,
        "up": up, "down": down, "nodes": nodes,
        "hx": hx, "hy": hy, "hz": hz, "hn": hn,
        "bottlenecks": [],
        "nPipes": len(model.links), "nChambers": len(model.chambers),
        "nHouses": len(hx), "baseDwellings": model.base_dwellings,
        "metres": round(sum(model.metres.values()), 1),
    }


def region_context(geometry):
    """Build the optional whole-domain context around the study segment."""
    import sim25

    model = sim25.Sim25Model(sim25.Case(), whole=True)
    network = model.net
    segment = set(network.upstream_pipes(sim25.SEGMENT_OUTLET))
    segment_nodes = {network.pipes[i].up for i in segment}
    segment.add(network.nodes[sim25.SEGMENT_OUTLET].outs[0])
    ox, oy, oz = geometry["ox"], geometry["oy"], geometry["oz"]

    def quantise(x, y):
        return int(round((x - ox) * 10)), int(round((y - oy) * 10))

    px, py, ptr, zu, zd = [], [], [], [], []
    for pipe_id in model._pipe_ids:
        if pipe_id in segment:
            continue
        pipe = network.pipes[pipe_id]
        ptr.append(len(px))
        for x, y in pipe.line:
            qx, qy = quantise(x, y)
            px.append(qx)
            py.append(qy)
        zu.append(int(round((pipe.inv_up - oz) * 100)))
        zd.append(int(round((pipe.inv_down - oz) * 100)))
    ptr.append(len(px))

    entries = []
    for entry in model.entries:
        node = network.nodes[entry["node"]]
        x, y = quantise(node.x, node.y)
        entries.append({
            "x": x, "y": y, "z": int(round((node.invert - oz) * 100)),
            "m": round(entry["length_m"]), "into": entry["node"] in segment_nodes,
        })
    return {
        "px": px, "py": py, "ptr": ptr, "zu": zu, "zd": zd,
        "nPipes": len(zu),
        "nChambers": sum(1 for node in model.nodes.values() if node.kind == "chamber"),
        "nLinks": len(model.links), "entries": entries,
    }


def build_runs():
    import catchment
    import sim25
    import sim25_grid
    from network import Network

    summaries = {}
    for filename in glob.glob(os.path.join(GRID, "ii*", "summary.json")):
        summary = json.load(io.open(filename, encoding="utf-8"))
        summaries[summary["tag"]] = summary
    order = [case.tag() for case in sim25_grid.cases("all")]
    missing = [tag for tag in order if tag not in summaries]
    if missing:
        sys.exit("missing grid cases: " + ", ".join(missing))

    corridor = []
    pattern = os.path.join(GRID, "corridor", "*", "summary.json")
    for filename in sorted(glob.glob(pattern)):
        corridor.append(json.load(io.open(filename, encoding="utf-8")))

    geometry = catchment_geometry(sim25.SEGMENT_OUTLET)
    geometry["context"] = region_context(geometry)
    names = sorted(node["name"] for node in geometry["nodes"] if node["kind"] == "chamber")
    manhole_index = {int(name[2:]): i for i, name in enumerate(names)}
    base_model = catchment.Catchment(Network(), sim25.SEGMENT_OUTLET)
    sizes = sorted({row["dwellings"] for row in summaries[order[0]]["rows"]})

    cases, cells, pooled = [], [], {}
    for case_id, tag in enumerate(order):
        summary = summaries[tag]
        cases.append({
            "id": case_id, "tag": tag, "ii": summary["case"]["ii"],
            "label": case_label(summary["case"]),
            "note": WEATHER_NOTE.get(round(summary["case"]["ii"], 2), ""),
            "method": summary["method"],
        })
        base_alarm = sorted(manhole_index[m] for m in summary["baseline"]["alarm"])
        for dwellings in sizes:
            rows = [row for row in summary["rows"] if row["dwellings"] == dwellings]
            for rule_id, _label, _note in RULES:
                if rule_id == "alarm":
                    tips = [(manhole_index[row["site"]],
                             sorted(manhole_index[m] for m in row["alarm"])) for row in rows]
                    baseline = base_alarm
                else:
                    threshold = float(rule_id[1:])
                    tips = [(manhole_index[row["site"]],
                             sorted(manhole_index[int(m)] for m, rise in row["rise_mm"].items()
                                    if rise >= threshold)) for row in rows]
                    baseline = []
                cells.append({
                    "case": case_id, "add": dwellings, "rule": rule_id, "base": baseline,
                    "rows": [{"site": site, "tip": tip} for site, tip in tips],
                })
                pooled.setdefault(rule_id, {}).setdefault(case_id, []).extend(
                    tip for _site, tip in tips)

    heat, sensors = {}, {}
    for rule_id, _label, _note in RULES:
        heat[rule_id], sensors[rule_id] = placement(
            [pooled[rule_id][case_id] for case_id in range(len(order))], len(names))

    corridor_rows = [{
        "ii": item["case"]["ii"],
        "label": WEATHER_LABEL.get(round(item["case"]["ii"], 2), ""),
        "rows": [{
            "dwellings": row["dwellings"],
            "outletRiseMm": round(row["outlet_head_rise_m"] * 1000, 1),
            "maxRiseMm": round(row["max_depth_rise_m"] * 1000, 1),
            "newlyAlarm": [manhole_index[m] for m in row["alarm"]],
        } for row in item["rows"]],
    } for item in corridor]

    runs = {
        "outlet": sim25.SEGMENT_OUTLET, "chambers": names,
        "manholeIds": [int(name[2:]) for name in names],
        "dwellingsAt": [base_model.dwellings.get(name, 0) for name in names],
        "cases": cases, "growthLevels": sizes,
        "rules": [{"id": rule, "label": label, "note": note}
                  for rule, label, note in RULES],
        "cells": cells, "heat": heat, "sensors": sensors, "corridor": corridor_rows,
    }
    return geometry, runs, len(cells)


def compare_output(output):
    expected = PAGE_FILES + [".nojekyll", "data/catchment.js", "data/growth.js", "data/index.js"]
    different = []
    for relative in expected:
        built = os.path.join(output, *relative.split("/"))
        published = os.path.join(TEMPLATE, *relative.split("/"))
        if not os.path.isfile(built) or not filecmp.cmp(built, published, shallow=False):
            different.append(relative)
    if different:
        print("DIFFERENT from the published page: " + ", ".join(different))
        return False
    print(f"byte-for-byte match: {len(expected)} published files")
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=os.path.join(ROOT, "reproduced_simulation25"))
    parser.add_argument("--check", action="store_true",
                        help="compare the rebuilt files with the tracked published page")
    args = parser.parse_args()
    output = os.path.abspath(args.out)
    if output == os.path.abspath(TEMPLATE):
        sys.exit("refusing to overwrite simulation25; choose a separate --out directory")

    data_dir = os.path.join(output, "data")
    os.makedirs(data_dir, exist_ok=True)
    geometry, runs, cell_count = build_runs()
    sizes = {
        "data/catchment.js": write_js(os.path.join(data_dir, "catchment.js"),
                                      "GROWTH_GEOM", geometry),
        "data/growth.js": write_js(os.path.join(data_dir, "growth.js"), "GROWTH_RUNS", runs),
    }
    for name in PAGE_FILES:
        shutil.copyfile(os.path.join(TEMPLATE, name), os.path.join(output, name))
        sizes[name] = os.path.getsize(os.path.join(output, name))
    shutil.copyfile(os.path.join(TEMPLATE, "data", "index.js"),
                    os.path.join(data_dir, "index.js"))
    sizes["data/index.js"] = os.path.getsize(os.path.join(data_dir, "index.js"))
    io.open(os.path.join(output, ".nojekyll"), "w", encoding="utf-8", newline="\n").write("")

    total = sum(sizes.values())
    for name, size in sizes.items():
        print(f"  {name:22s} {size / 1024:8.0f} KB")
    print(f"  {'total':22s} {total / 1024 / 1024:8.2f} MB; {cell_count} cells")
    print("-> " + output)
    if args.check and not compare_output(output):
        sys.exit(1)


if __name__ == "__main__":
    main()
