#!/usr/bin/env python3
"""Rebuild the published Sim 2.5 browser page from the public simulation outputs.

This is the public, self-contained counterpart of the project's private page builder. It
does not run SWMM. It converts the saved grid under simulation_src/results/sim25/grid into
the static JavaScript payload used by the browser and reconstructs the network geometry
from the exact public ArcGIS snapshot under simulation_src/data/raw.

The already-public HTML, JavaScript UI, and narrative content in simulation25 are treated
as page templates. The numerical catchment.js and growth.js files are regenerated.

Examples:
    python tools/build_sim25_web.py
    python tools/build_sim25_web.py --out reproduced_simulation25 --check
"""
import argparse
import filecmp
import glob
import io
import json
import os
import shutil
import sys


HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SIM = os.path.join(ROOT, "simulation_src")
GRID = os.path.join(SIM, "results", "sim25", "grid")
TEMPLATE = os.path.join(ROOT, "simulation25")
sys.path.insert(0, SIM)

PAGE_FILES = ["index.html", "growth_ui.js", "growth_3d.js"]
MAX_SENSORS = 10
# Case names and notes come from the same cases.json the grid ran from, so what the page
# calls a case can never drift from what was actually solved.
CASES_FILE = os.path.join(SIM, "cases.json")
with io.open(CASES_FILE, encoding="utf-8") as _f:
    _CASES = json.load(_f)
# The study area decides which grid this build reads and what the map draws. Its results
# live in a folder of their own, the same choice sim25_grid.py makes, so the two never mix.
STUDY_AREA = _CASES.get("study_area", "segment")
if STUDY_AREA == "whole":
    GRID = os.path.join(SIM, "results", "sim25", "grid_whole")
WEATHER_LABEL = {round(w["ii"], 2): w["label"] for w in _CASES["weather"]}
WEATHER_NOTE = {round(w["ii"], 2): w["note"] for w in _CASES["weather"]}
VARIANTS = (_CASES.get("sensitivity") or {}).get("variants", [])
RULES = [
    ("alarm", "150 mm alarm", "Seen when the depth newly passes 150 mm above the pipe floor "
     "(the low alarm used in a real deployment)."),
    ("r10", "Rise 10 mm", "Seen when the depth rises at least 10 mm over that manhole's "
     "own level before the growth."),
    ("r25", "Rise 25 mm", "Seen when the depth rises at least 25 mm over that manhole's "
     "own level before the growth."),
    ("r50", "Rise 50 mm", "Seen when the depth rises at least 50 mm over that manhole's "
     "own level before the growth."),
]


def write_js(path, varname, payload):
    body = json.dumps(payload, separators=(",", ":"), allow_nan=False)
    text = (
        "// Generated by tools/build_sim25_web.py - do not edit by hand.\n"
        "// EPA SWMM output, quantised and base64 packed. The physics is SWMM's;\n"
        "// this file is only its saved answer.\n"
        f"window.{varname} = {body};\n"
    )
    io.open(path, "w", encoding="utf-8", newline="\n").write(text)
    return len(text.encode("utf-8"))


def case_label(case):
    """Weather name, plus the label of every configured variant this case matches. A case
    matches a variant when it carries every field that variant sets, so the label is
    rebuilt from what the summary.json says was run, not from a separate list of names."""
    label = WEATHER_LABEL.get(round(case["ii"], 2), f"I&I {case['ii']}")
    extra = [v["label"] for v in VARIANTS
             if all(case.get(k) == val for k, val in v["set"].items())]
    return label + (" + " + ", ".join(extra) if extra else "")


def placement(per_case, n_chambers, k_max=MAX_SENSORS):
    """Choose nested 1-to-k sensor sets and derive the single-sensor heatmap."""
    cases = [[set(tips) for tips in sets if tips] for sets in per_case]
    cases = [case for case in cases if case]
    alone = []
    for manhole in range(n_chambers):
        fractions = [sum(1 for tips in case if manhole in tips) / len(case) for case in cases]
        alone.append(fractions)
    heat = {
        "worst": [round(min(fractions), 4) for fractions in alone],
        "mean": [round(sum(fractions) / len(fractions), 4) for fractions in alone],
    }

    def cover(chosen):
        return [sum(1 for tips in case if tips & chosen) / len(case) for case in cases]

    result = {}
    for objective in ("mean", "worst"):
        chosen, order, worst, mean = set(), [], [], []
        for _ in range(k_max):
            best, best_key = None, None
            for manhole in range(n_chambers):
                if manhole in chosen:
                    continue
                fractions = cover(chosen | {manhole})
                if objective == "mean":
                    key = (sum(fractions) / len(fractions), min(fractions))
                else:
                    key = (min(fractions), sum(fractions) / len(fractions))
                if best_key is None or key > best_key:
                    best, best_key = manhole, key
            chosen.add(best)
            order.append(best)
            fractions = cover(chosen)
            worst.append(round(min(fractions), 4))
            mean.append(round(sum(fractions) / len(fractions), 4))
        result[objective] = {"order": order, "worst": worst, "mean": mean}
    return heat, result


def catchment_geometry(outlet):
    """Build drawing geometry from the same Catchment object supplied to SWMM."""
    from network import Network
    import catchment

    network = Network()
    model = catchment.Catchment(network, outlet)
    xs = [point[0] for link in model.links for point in link.line]
    ys = [point[1] for link in model.links for point in link.line]
    zs = [value for link in model.links for value in (link.inv_up, link.inv_down)]
    ox, oy, oz = min(xs), min(ys), min(zs)

    px, py, ptr, zu, zd, dia, up, down = [], [], [], [], [], [], [], []
    names = list(model.nodes)
    index = {name: i for i, name in enumerate(names)}
    for link in model.links:
        ptr.append(len(px))
        for x, y in link.line:
            px.append(int(round((x - ox) * 10)))
            py.append(int(round((y - oy) * 10)))
        zu.append(int(round((link.inv_up - oz) * 100)))
        zd.append(int(round((link.inv_down - oz) * 100)))
        dia.append(int(round(link.dia * 1000)))
        up.append(index[link.up])
        down.append(index[link.down])
    ptr.append(len(px))

    nodes = []
    for name in names:
        node = model.nodes[name]
        nodes.append({
            "name": name,
            "kind": node.kind,
            "x": int(round((node.x - ox) * 10)),
            "y": int(round((node.y - oy) * 10)),
            "inv": int(round((node.invert - oz) * 100)),
            "depth": round(node.max_depth, 3),
            "mh": node.manhole_id,
            "dw": model.dwellings.get(name, 0),
        })

    study_assets = {pipe.asset_id for pipe in model.pipes if pipe.role == "study"}
    in_model = {i for i, pipe in enumerate(network.pipes) if pipe.asset_id in study_assets}
    hx, hy, hz, hn, jx, jy = [], [], [], [], [], []
    junctions = getattr(network, "connection_junctions", None) or []
    for k, (x, y, pipe_id) in enumerate(getattr(network, "connections", [])):
        if pipe_id in in_model:
            pipe = network.pipes[pipe_id]
            hx.append(int(round((x - ox) * 10)))
            hy.append(int(round((y - oy) * 10)))
            hz.append(int(round(((pipe.inv_up + pipe.inv_down) / 2 - oz) * 100)))
            hn.append(index[model.node_of[pipe.up]])
            j = junctions[k] if k < len(junctions) and junctions[k] else (x, y)
            jx.append(int(round((j[0] - ox) * 10)))
            jy.append(int(round((j[1] - oy) * 10)))

    outlet_name = model.node_of.get(outlet)
    return {
        "outletName": outlet_name,
        "outletManhole": model.nodes[outlet_name].manhole_id if outlet_name else None,
        "ox": round(ox, 2), "oy": round(oy, 2), "oz": round(oz, 3),
        "px": px, "py": py, "ptr": ptr, "zu": zu, "zd": zd, "dia": dia,
        "up": up, "down": down, "nodes": nodes,
        "hx": hx, "hy": hy, "hz": hz, "hn": hn,
        **link_details(model),
        # Where each property joins its main: the lateral the page draws from the house.
        "jx": jx, "jy": jy,
        "bottlenecks": [],
        "nPipes": len(model.links), "nChambers": len(model.chambers),
        "nHouses": len(hx), "baseDwellings": model.base_dwellings,
        "metres": round(sum(model.metres.values()), 1),
    }


def link_details(model):
    """What a click on a pipe shows: one entry per drawn link, from the pipe it belongs to.

    A long pipe may be split into several links; each carries its whole pipe's details,
    so clicking any piece of it reads the same. Capacity is full-bore Manning, the
    pipe's own published grade and the roughness model.py gives its material, the same n
    SWMM solves with. A flat or adverse grade has no gravity full-bore capacity, so it is
    left empty rather than shown as zero."""
    import math
    import model as swmm_model

    by_label = {pipe.label: pipe for pipe in model.pipes}
    out = {"pid": [], "pmat": [], "pyr": [], "plen": [], "pslope": [], "pcap": []}
    for link in model.links:
        pipe = by_label.get(link.pipe)
        if pipe is None:                       # an outfall dummy: no published pipe
            for key in out:
                out[key].append(None)
            continue
        d, s = pipe.dia, pipe.slope
        cap = None
        if d and s and s > 0:
            n = swmm_model.manning_of(pipe.material)
            area, radius = math.pi * d * d / 4, d / 4
            cap = round(1000 * area * radius ** (2 / 3) * math.sqrt(s) / n, 1)
        out["pid"].append(pipe.asset_id)
        out["pmat"].append(pipe.material or None)
        out["pyr"].append(pipe.year or None)
        out["plen"].append(round(pipe.length, 1))
        out["pslope"].append(round(100 * s, 2) if s is not None else None)
        out["pcap"].append(cap)
    return out


def domain_geometry():
    """Drawing geometry for the whole study area: the model domain SWMM itself solves.

    catchment_geometry draws the gravity catchment above one node, which is right for the
    segment but cannot hold the whole domain: three pump-station catchments join it through
    rising mains, not gravity pipes. This reads the whole-domain Sim25Model instead, so the
    map is exactly the network the grid ran on, in the format the page already reads."""
    import sim25

    model = sim25.Sim25Model(sim25.Case(), whole=True)
    network = model.net
    links = model.links
    xs = [point[0] for link in links for point in link.line]
    ys = [point[1] for link in links for point in link.line]
    zs = [value for link in links for value in (link.inv_up, link.inv_down)]
    ox, oy, oz = min(xs), min(ys), min(zs)

    # Dwellings per node, attached as sim25 attaches the sewage load: each pipe's connected
    # dwellings at the pipe's upstream node, exit pipes excluded.
    dwellings = {}
    for pipe_id in model._pipe_ids:
        if pipe_id in model._exits:
            continue
        pipe = network.pipes[pipe_id]
        name = model.node_of.get(pipe.up)
        if name is not None:
            dwellings[name] = dwellings.get(name, 0) + pipe.dwellings

    px, py, ptr, zu, zd, dia, up, down = [], [], [], [], [], [], [], []
    names = list(model.nodes)
    index = {name: i for i, name in enumerate(names)}
    for link in links:
        ptr.append(len(px))
        for x, y in link.line:
            px.append(int(round((x - ox) * 10)))
            py.append(int(round((y - oy) * 10)))
        zu.append(int(round((link.inv_up - oz) * 100)))
        zd.append(int(round((link.inv_down - oz) * 100)))
        dia.append(int(round(link.dia * 1000)))
        up.append(index[link.up])
        down.append(index[link.down])
    ptr.append(len(px))

    nodes = [{
        "name": name, "kind": node.kind,
        "x": int(round((node.x - ox) * 10)), "y": int(round((node.y - oy) * 10)),
        "inv": int(round((node.invert - oz) * 100)), "depth": round(node.max_depth, 3),
        "mh": node.manhole_id, "dw": dwellings.get(name, 0),
    } for name, node in model.nodes.items()]

    in_model = set(model._pipe_ids)
    hx, hy, hz, hn, jx, jy = [], [], [], [], [], []
    junctions = getattr(network, "connection_junctions", None) or []
    for k, (x, y, pipe_id) in enumerate(getattr(network, "connections", [])):
        if pipe_id in in_model:
            pipe = network.pipes[pipe_id]
            name = model.node_of.get(pipe.up)
            if name is None:
                continue
            hx.append(int(round((x - ox) * 10)))
            hy.append(int(round((y - oy) * 10)))
            hz.append(int(round(((pipe.inv_up + pipe.inv_down) / 2 - oz) * 100)))
            hn.append(index[name])
            j = junctions[k] if k < len(junctions) and junctions[k] else (x, y)
            jx.append(int(round((j[0] - ox) * 10)))
            jy.append(int(round((j[1] - oy) * 10)))

    outlet_name = model.node_of.get(sim25.DOMAIN_END)
    return {
        "outletName": outlet_name,
        # The domain ends where the council data does, at an outfall, not at a manhole.
        "outletManhole": model.nodes[outlet_name].manhole_id if outlet_name else None,
        "ox": round(ox, 2), "oy": round(oy, 2), "oz": round(oz, 3),
        "px": px, "py": py, "ptr": ptr, "zu": zu, "zd": zd, "dia": dia,
        "up": up, "down": down, "nodes": nodes,
        "hx": hx, "hy": hy, "hz": hz, "hn": hn,
        **link_details(model),
        # Where each property joins its main: the lateral the page draws from the house.
        "jx": jx, "jy": jy,
        "bottlenecks": [],
        "nPipes": len(links), "nChambers": len(model.chambers),
        "nHouses": len(hx), "baseDwellings": sum(dwellings.values()),
        "metres": round(sum(link.length for link in links), 1),
    }


def whole_area_context(geometry):
    """Context for the whole area. Every modelled pipe is already in the study area, so there
    are no grey "rest of the network" pipes to draw: drawing the council pipes the model does
    not contain under that legend would call them solved when they are not. What is left to
    show is where outside pipes flow in, and in the whole area every one flows into it."""
    import sim25

    model = sim25.Sim25Model(sim25.Case(), whole=True)
    ox, oy, oz = geometry["ox"], geometry["oy"], geometry["oz"]
    entries = []
    for entry in model.entries:
        node = model.net.nodes[entry["node"]]
        entries.append({
            "x": int(round((node.x - ox) * 10)), "y": int(round((node.y - oy) * 10)),
            "z": int(round((node.invert - oz) * 100)),
            "m": round(entry["length_m"]), "into": True,
        })
    return {"px": [], "py": [], "ptr": [0], "zu": [], "zd": [], "nPipes": 0,
            "nChambers": sum(1 for node in model.nodes.values() if node.kind == "chamber"),
            "nLinks": len(model.links), "entries": entries}


def region_context(geometry):
    """Build the optional whole-domain context around the study segment."""
    import sim25

    model = sim25.Sim25Model(sim25.Case(), whole=True)
    network = model.net
    segment = set(network.upstream_pipes(sim25.SEGMENT_OUTLET))
    segment_nodes = {network.pipes[i].up for i in segment}
    segment.add(network.nodes[sim25.SEGMENT_OUTLET].outs[0])
    ox, oy, oz = geometry["ox"], geometry["oy"], geometry["oz"]

    def quantise(x, y):
        return int(round((x - ox) * 10)), int(round((y - oy) * 10))

    px, py, ptr, zu, zd = [], [], [], [], []
    for pipe_id in model._pipe_ids:
        if pipe_id in segment:
            continue
        pipe = network.pipes[pipe_id]
        ptr.append(len(px))
        for x, y in pipe.line:
            qx, qy = quantise(x, y)
            px.append(qx)
            py.append(qy)
        zu.append(int(round((pipe.inv_up - oz) * 100)))
        zd.append(int(round((pipe.inv_down - oz) * 100)))
    ptr.append(len(px))

    entries = []
    for entry in model.entries:
        node = network.nodes[entry["node"]]
        x, y = quantise(node.x, node.y)
        entries.append({
            "x": x, "y": y, "z": int(round((node.invert - oz) * 100)),
            "m": round(entry["length_m"]), "into": entry["node"] in segment_nodes,
        })
    return {
        "px": px, "py": py, "ptr": ptr, "zu": zu, "zd": zd,
        "nPipes": len(zu),
        "nChambers": sum(1 for node in model.nodes.values() if node.kind == "chamber"),
        "nLinks": len(model.links), "entries": entries,
    }


def build_runs():
    import catchment
    import sim25
    import sim25_grid
    from network import Network

    summaries = {}
    for filename in glob.glob(os.path.join(GRID, "ii*", "summary.json")):
        summary = json.load(io.open(filename, encoding="utf-8"))
        summaries[summary["tag"]] = summary
    order = [case.tag() for case in sim25_grid.cases("all")]
    missing = [tag for tag in order if tag not in summaries]
    if missing:
        sys.exit("\ncases.json lists cases that have never been solved, so there is nothing to "
                 "publish for them:\n" + "".join(f"  {tag}\n" for tag in missing) +
                 "Run them first, from simulation_src/ (each is about 4 to 20 minutes):\n"
                 "  python sim25_grid.py --cases all --resume\n"
                 "--resume skips every case that already has results.")

    # The corridor runs one case per weather level, so publish only the levels cases.json
    # still lists. Globbing everything on disk would keep showing a level after it was
    # removed from the config, which is the same mistake the grid order above avoids.
    levels = {round(ii, 2) for ii, _ in sim25.WEATHER}
    corridor = []
    pattern = os.path.join(GRID, "corridor", "*", "summary.json")
    for filename in sorted(glob.glob(pattern)):
        item = json.load(io.open(filename, encoding="utf-8"))
        if round(item["case"]["ii"], 2) in levels:
            corridor.append(item)

    whole_area = STUDY_AREA == "whole"
    if whole_area:
        geometry = domain_geometry()
        geometry["context"] = whole_area_context(geometry)
    else:
        geometry = catchment_geometry(sim25.SEGMENT_OUTLET)
        geometry["context"] = region_context(geometry)
    names = sorted(node["name"] for node in geometry["nodes"] if node["kind"] == "chamber")
    manhole_index = {int(name[2:]): i for i, name in enumerate(names)}
    base_model = None if whole_area else catchment.Catchment(Network(), sim25.SEGMENT_OUTLET)
    node_dw = {node["name"]: node["dw"] for node in geometry["nodes"]}
    sizes = sorted({row["dwellings"] for row in summaries[order[0]]["rows"]})

    cases, cells, pooled = [], [], {}
    for case_id, tag in enumerate(order):
        summary = summaries[tag]
        cases.append({
            "id": case_id, "tag": tag, "ii": summary["case"]["ii"],
            "label": case_label(summary["case"]),
            "note": WEATHER_NOTE.get(round(summary["case"]["ii"], 2), ""),
            "method": summary["method"],
        })
        base_alarm = sorted(manhole_index[m] for m in summary["baseline"]["alarm"])
        for dwellings in sizes:
            rows = [row for row in summary["rows"] if row["dwellings"] == dwellings]
            for rule_id, _label, _note in RULES:
                if rule_id == "alarm":
                    tips = [(manhole_index[row["site"]],
                             sorted(manhole_index[m] for m in row["alarm"])) for row in rows]
                    baseline = base_alarm
                else:
                    threshold = float(rule_id[1:])
                    tips = [(manhole_index[row["site"]],
                             sorted(manhole_index[int(m)] for m, rise in row["rise_mm"].items()
                                    if rise >= threshold)) for row in rows]
                    baseline = []
                cells.append({
                    "case": case_id, "add": dwellings, "rule": rule_id, "base": baseline,
                    "rows": [{"site": site, "tip": tip} for site, tip in tips],
                })
                pooled.setdefault(rule_id, {}).setdefault(case_id, []).extend(
                    tip for _site, tip in tips)

    heat, sensors = {}, {}
    for rule_id, _label, _note in RULES:
        heat[rule_id], sensors[rule_id] = placement(
            [pooled[rule_id][case_id] for case_id in range(len(order))], len(names))

    corridor_rows = [{
        "ii": item["case"]["ii"],
        "label": WEATHER_LABEL.get(round(item["case"]["ii"], 2), ""),
        "rows": [{
            "dwellings": row["dwellings"],
            "outletRiseMm": round(row["outlet_head_rise_m"] * 1000, 1),
            "maxRiseMm": round(row["max_depth_rise_m"] * 1000, 1),
            "newlyAlarm": [manhole_index[m] for m in row["alarm"]],
        } for row in item["rows"]],
    } for item in corridor]

    runs = {
        "outlet": sim25.DOMAIN_END if whole_area else sim25.SEGMENT_OUTLET,
        "chambers": names,
        "manholeIds": [int(name[2:]) for name in names],
        "dwellingsAt": ([node_dw.get(name, 0) for name in names] if whole_area
                        else [base_model.dwellings.get(name, 0) for name in names]),
        "cases": cases, "growthLevels": sizes,
        "rules": [{"id": rule, "label": label, "note": note}
                  for rule, label, note in RULES],
        "cells": cells, "heat": heat, "sensors": sensors, "corridor": corridor_rows,
    }
    if whole_area:
        # Only the whole area says so, so a segment build stays byte-identical to the page
        # published before the setting existed.
        runs["studyArea"] = "whole"
    return geometry, runs, len(cells)


def compare_output(output):
    expected = PAGE_FILES + [".nojekyll", "data/catchment.js", "data/growth.js", "data/index.js"]
    different = []
    for relative in expected:
        built = os.path.join(output, *relative.split("/"))
        published = os.path.join(TEMPLATE, *relative.split("/"))
        if not os.path.isfile(built) or not filecmp.cmp(built, published, shallow=False):
            different.append(relative)
    if different:
        print("DIFFERENT from the published page: " + ", ".join(different))
        return False
    print(f"byte-for-byte match: {len(expected)} published files")
    return True


def bump_cache_keys():
    """Move every Sim 2.5 cache key to one new number, past the highest in use.

    simulation25/index.html says its script keys must match the landing page's iframe key
    and that both are bumped together on every publish. Going past the highest rather than
    adding one to each keeps them equal even if they had drifted, and never reuses a number
    a browser may already hold a stale copy under."""
    import re
    page, home = os.path.join(TEMPLATE, "index.html"), os.path.join(ROOT, "index.html")
    page_src = io.open(page, encoding="utf-8").read()
    home_src = io.open(home, encoding="utf-8").read()
    script = re.compile(r'(<script src="(?:data/)?[\w.]+\.js)\?v=(\d+)"')
    iframe = re.compile(r'(simulation25/index\.html)\?v=(\d+)')
    used = [int(m.group(2)) for m in script.finditer(page_src)]
    used += [int(m.group(2)) for m in iframe.finditer(home_src)]
    new = max(used) + 1
    page_src = script.sub(lambda m: f'{m.group(1)}?v={new}"', page_src)
    home_src = iframe.sub(lambda m: f"{m.group(1)}?v={new}", home_src)
    io.open(page, "w", encoding="utf-8", newline="\n").write(page_src)
    io.open(home, "w", encoding="utf-8", newline="\n").write(home_src)
    return new


def publish(output, runs):
    """Copy the two generated data files into the tracked page, and bump the keys.

    Only data/catchment.js and data/growth.js are copied. The HTML and UI modules are the
    templates this build reads, so they already are what is published."""
    changed = []
    for name in ("catchment.js", "growth.js"):
        src = os.path.join(output, "data", name)
        dst = os.path.join(TEMPLATE, "data", name)
        if not os.path.exists(dst) or not filecmp.cmp(src, dst, shallow=False):
            shutil.copyfile(src, dst)
            changed.append("data/" + name)
    if not changed:
        print("\nPublished page already matches this build; nothing copied, keys unchanged.")
        return
    key = bump_cache_keys()
    print(f"\nPublished into simulation25/: {', '.join(changed)}; cache keys now v={key}.")
    print(f"{len(runs['cases'])} cases on the page:")
    for case in runs["cases"]:
        print(f"  - {case['label']}")
    print("Reload the Simulation 2.5 tab to see them.")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=os.path.join(ROOT, "reproduced_simulation25"))
    parser.add_argument("--check", action="store_true",
                        help="compare the rebuilt files with the tracked published page")
    parser.add_argument("--publish", action="store_true",
                        help="after building, copy the data into simulation25/ and bump its "
                             "cache keys, so the page you are viewing shows this build")
    args = parser.parse_args()
    output = os.path.abspath(args.out)
    if output == os.path.abspath(TEMPLATE):
        sys.exit("refusing to overwrite simulation25; choose a separate --out directory")

    data_dir = os.path.join(output, "data")
    os.makedirs(data_dir, exist_ok=True)
    try:
        geometry, runs, cell_count = build_runs()
    except ValueError as e:
        # A mistake in cases.json. Say so plainly rather than with a traceback.
        sys.exit(f"\ncases.json is not valid, so nothing was built or published:\n  {e}")
    sizes = {
        "data/catchment.js": write_js(os.path.join(data_dir, "catchment.js"),
                                      "GROWTH_GEOM", geometry),
        "data/growth.js": write_js(os.path.join(data_dir, "growth.js"), "GROWTH_RUNS", runs),
    }
    for name in PAGE_FILES:
        shutil.copyfile(os.path.join(TEMPLATE, name), os.path.join(output, name))
        sizes[name] = os.path.getsize(os.path.join(output, name))
    shutil.copyfile(os.path.join(TEMPLATE, "data", "index.js"),
                    os.path.join(data_dir, "index.js"))
    sizes["data/index.js"] = os.path.getsize(os.path.join(data_dir, "index.js"))
    io.open(os.path.join(output, ".nojekyll"), "w", encoding="utf-8", newline="\n").write("")

    total = sum(sizes.values())
    for name, size in sizes.items():
        print(f"  {name:22s} {size / 1024:8.0f} KB")
    print(f"  {'total':22s} {total / 1024 / 1024:8.2f} MB; {cell_count} cells")
    print("-> " + output)
    if args.check and not compare_output(output):
        sys.exit(1)
    if args.publish:
        publish(output, runs)


if __name__ == "__main__":
    main()
