#!/usr/bin/env python3
"""
validate_blockage_timeline.py — Cross-validation of the real-time blockage timeline
against offline EPA SWMM 5.2 dynamic-wave simulation.

This tool executes authentic 1D hydrodynamic dynamic-wave differential equation
solves (via pyswmm / SWMM 5.2.4) across representative sewer blockage scenarios in the
Walkerville catchment. It compares SWMM's time-dependent water depth and spill horizon
curves against the client-side closed-form hydraulic model (BlockagePhysics in
simulation/model/blockage_physics.js).
"""

import os
import sys
import json
import math
import tempfile
import subprocess
from datetime import datetime

try:
    from pyswmm import Simulation, Nodes, Links
    from swmm.toolkit import solver
except ImportError:
    print("Error: pyswmm is required. Install via `pip install pyswmm`.")
    sys.exit(1)

# Ensure SWMM is stock EPA build
SWMM_VER = solver.swmm_get_version()
print(f"Loaded EPA SWMM 5.2 Engine Build: {SWMM_VER} (Stock EPA 5.2.4)")

# Validation Scenarios (Gap E)
SCENARIOS = [
    {
        "id": "SC-01",
        "name": "Bottleneck Trunk Choke (Severe)",
        "pipe": 101,
        "severity": 80,
        "note": "Critical network bottleneck #101, 150 mm, slope 0.84%, 214 tributary homes",
    },
    {
        "id": "SC-02",
        "name": "Main Trunk Collector (Moderate-Heavy)",
        "pipe": 3,
        "severity": 60,
        "note": "Major 225 mm trunk main, flat slope 0.34%, 447 tributary homes",
    },
    {
        "id": "SC-03",
        "name": "Collector Fatberg Choke (Near-Total)",
        "pipe": 15,
        "severity": 95,
        "note": "Sub-catchment collector #15, 150 mm, gentle slope 0.49%, 22 tributary homes",
    },
    {
        "id": "SC-04",
        "name": "Steep Lateral Intrusion (Mid-Range)",
        "pipe": 140,
        "severity": 50,
        "note": "Steep branch main #140, 150 mm, steep slope 2.77%, 22 tributary homes",
    },
    {
        "id": "SC-05",
        "name": "Downstream Trunk Inflow (Mild)",
        "pipe": 2,
        "severity": 25,
        "note": "Downstream 225 mm trunk #2, slope 0.33%, 626 tributary homes",
    },
    {
        "id": "SC-06",
        "name": "Small Diameter Lateral (High)",
        "pipe": 39,
        "severity": 75,
        "note": "Small 143 mm lateral #39, steep slope 5.25%, 5 tributary homes",
    },
]

def load_network_geometry():
    """Load real network geometry from simulation/data/catchment.js via Node."""
    cmd = ["node", "-e", "console.log(JSON.stringify(require('./simulation/data/catchment.js')));"]
    res = subprocess.check_output(cmd, cwd=os.getcwd())
    return json.loads(res)

def query_node_physics(pipe_idx, severity, ii_rate, timeline_sec):
    """Query pure JS BlockagePhysics module via Node."""
    script = f"""
    const BP = require('./simulation/model/blockage_physics.js');
    const g = require('./simulation/data/catchment.js');
    const state = BP.computeBlockageState({{
        geom: g,
        pipeIdx: {pipe_idx},
        severity: {severity},
        viscMode: 'domestic',
        iiRate: {ii_rate},
        timelineSec: {timeline_sec}
    }});
    console.log(JSON.stringify({{
        h0: state.h0,
        isSpill: state.isSpill,
        timeToSpillSec: state.timeToSpillSec,
        timeToSpillMin: state.timeToSpillMin,
        excessLps: state.excessLps,
        qCapLps: state.qCapLps,
        qChokedLps: state.qChokedLps,
        qInLps: state.qInLps,
        depthM: state.depthM,
        backwaterPipesCount: state.backwaterPipes.length,
        overflowingCount: state.overflowing.length
    }}));
    """
    cmd = ["node", "-e", script]
    res = subprocess.check_output(cmd, cwd=os.getcwd())
    return json.loads(res)

def build_swmm_inp(g, blocked_pipe_idx, severity_pct, ii_rate=0.25, duration_hrs=2.0):
    """
    Build an authentic EPA SWMM 5.2 input file (.inp).
    - Flow routing: Dynamic Wave (DYNWAVE)
    - Surcharge method: Preissmann Slot (SLOT)
    - Storage chambers: 1050 mm diameter (0.866 m²) functional storage nodes
    - Blocked conduit: constricted diameter Deff = D * (1 - sev/100)^(1.8 / 2.667)
    """
    # Constriction mechanism (Gap D):
    # Setting Deff = D * (1 - sev/100)^0.675 matches the normal-depth Manning capacity
    # Q_choked = Q_cap * (1 - sev/100)^1.8, isolating dynamic-wave unsteady routing deltas.
    exp_factor = 1.8 / (8.0 / 3.0)  # 0.675

    inp = f""";; EPA SWMM 5.2 Dynamic Wave Simulation Model
;; Generated by tools/validate_blockage_timeline.py
[TITLE]
Walkerville Sewer Blockage Dynamic Wave Validation
Scenario: Blocked Pipe #{blocked_pipe_idx} @ {severity_pct}% Severity

[OPTIONS]
FLOW_UNITS           LPS
INFILTRATION         HORTON
FLOW_ROUTING         DYNWAVE
LINK_OFFSETS         DEPTH
MIN_SLOPE            0.0015
ALLOW_PONDING        NO
SKIP_STEADY_STATE    NO
START_DATE           01/01/2026
START_TIME           00:00:00
REPORT_START_DATE    01/01/2026
REPORT_START_TIME    00:00:00
END_DATE             01/01/2026
END_TIME             {int(duration_hrs):02d}:00:00
REPORT_STEP          00:00:30
ROUTING_STEP         0.5
SURCHARGE_METHOD     SLOT
INERTIAL_DAMPING     PARTIAL
NORMAL_FLOW_LIMITED  BOTH
VARIABLE_STEP        0.75
MINIMUM_STEP         0.5

[JUNCTIONS]
;;Name           Elevation  MaxDepth   InitDepth  SurDepth   Aponded
"""

    for n in g["nodes"]:
        nm = n["name"]
        kind = n.get("kind", "")
        if kind not in ("outfall", "chamber"):
            elev = n["inv"] / 100.0
            depth = n.get("depth", 2.4) or 2.4
            inp += f"{nm}  {elev:.4f}  {depth:.4f}  0.0  0.0  0.0\n"

    inp += """
[STORAGE]
;;Name           Elevation  MaxDepth   InitDepth  Shape       A      B      C      Surcharge  Fevap
"""
    # Assumption H8: 1050 mm uniform circular shaft (0.866 m²)
    for n in g["nodes"]:
        nm = n["name"]
        kind = n.get("kind", "")
        if kind == "chamber":
            elev = n["inv"] / 100.0
            depth = n.get("depth", 2.4) or 2.4
            inp += f"{nm}  {elev:.4f}  {depth:.4f}  0.0  FUNCTIONAL  0.866  0.0  0.0  0.0  0.0\n"

    inp += """
[OUTFALLS]
;;Name           Elevation  Type       Stage Data       Gated    Route To
"""
    for n in g["nodes"]:
        nm = n["name"]
        kind = n.get("kind", "")
        if kind == "outfall":
            elev = n["inv"] / 100.0
            inp += f"{nm}  {elev:.4f}  FREE                        NO\n"

    inp += """
[CONDUITS]
;;Name           From Node        To Node          Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow
"""
    for p in range(g["nPipes"]):
        uNode = g["nodes"][g["up"][p]]["name"]
        dNode = g["nodes"][g["down"][p]]["name"]
        a, b = g["ptr"][p], g["ptr"][p + 1]
        length = 0.0
        for i in range(a, b - 1):
            dx = (g["px"][i + 1] - g["px"][i]) / 10.0
            dy = (g["py"][i + 1] - g["py"][i]) / 10.0
            length += math.hypot(dx, dy)
        length = max(15.0, length)
        in_off = max(0.0, g["zu"][p] / 100.0 - g["nodes"][g["up"][p]]["inv"] / 100.0)
        out_off = max(0.0, g["zd"][p] / 100.0 - g["nodes"][g["down"][p]]["inv"] / 100.0)
        inp += f"P{p}  {uNode}  {dNode}  {length:.2f}  0.013  {in_off:.4f}  {out_off:.4f}  0.0  0.0\n"

    inp += """
[XSECTIONS]
;;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert
"""
    for p in range(g["nPipes"]):
        dia = (g["dia"][p] or 150) / 1000.0
        if p == blocked_pipe_idx and severity_pct > 0:
            choke_mult = math.pow(max(0.01, 1.0 - severity_pct / 100.0), exp_factor)
            dia_choked = max(0.015, dia * choke_mult)
            inp += f"P{p}  CIRCULAR  {dia_choked:.4f}  0.0  0.0  0.0  1\n"
        else:
            inp += f"P{p}  CIRCULAR  {dia:.4f}  0.0  0.0  0.0  1\n"

    inp += """
[INFLOWS]
;;Node           Constituent      Time Series      Type     Mfactor  Sfactor  Base     Baseline
"""
    # 1. Base sanitary loads (500 L/dwelling/day * PF 2.0)
    dwelling_counts = {}
    for h_node in g.get("hn", []):
        node_name = g["nodes"][h_node]["name"]
        dwelling_counts[node_name] = dwelling_counts.get(node_name, 0) + 1

    # 2. Infiltration & Inflow (0.25 L/s per 100m upstream entry)
    pipe_ii = {}
    for p in range(g["nPipes"]):
        u_name = g["nodes"][g["up"][p]]["name"]
        a, b = g["ptr"][p], g["ptr"][p + 1]
        length = 0.0
        for i in range(a, b - 1):
            dx = (g["px"][i + 1] - g["px"][i]) / 10.0
            dy = (g["py"][i + 1] - g["py"][i]) / 10.0
            length += math.hypot(dx, dy)
        length = max(15.0, length)
        q_ii = length * (ii_rate / 100.0)
        pipe_ii[u_name] = pipe_ii.get(u_name, 0.0) + q_ii

    all_inflows = {}
    for name, homes in dwelling_counts.items():
        all_inflows[name] = all_inflows.get(name, 0.0) + homes * (500.0 * 2.0 / 86400.0)
    for name, q_ii in pipe_ii.items():
        all_inflows[name] = all_inflows.get(name, 0.0) + q_ii

    for node_name, q_total in all_inflows.items():
        if node_name != g["outletName"]:
            inp += f"{node_name}  FLOW  \"\"  FLOW  1.0  1.0  {q_total:.5f}\n"

    return inp

def run_validation():
    print("=" * 80)
    print("SIM2 HYDRAULICS: EPA SWMM 5.2 vs REAL-TIME APPROXIMATION CROSS-VALIDATION")
    print("=" * 80)

    g = load_network_geometry()
    print(f"Loaded catchment geometry: {g['nPipes']} pipes, {len(g['nodes'])} nodes, {g['baseDwellings']} dwellings.")

    results = []

    for sc in SCENARIOS:
        p_idx = sc["pipe"]
        sev = sc["severity"]
        u_node_name = g["nodes"][g["up"][p_idx]]["name"]
        u_node_depth = g["nodes"][g["up"][p_idx]].get("depth", 2.4) or 2.4

        print(f"\nRunning Scenario {sc['id']}: {sc['name']} (Pipe #{p_idx}, Choke {sev}%, Upstream: {u_node_name})")

        # 1. Generate and Run SWMM 5.2 Dynamic Wave Model
        inp_text = build_swmm_inp(g, p_idx, sev, ii_rate=0.25, duration_hrs=2.0)
        with tempfile.NamedTemporaryFile(mode="w", suffix=".inp", delete=False) as f:
            f.write(inp_text)
            temp_inp_path = f.name

        swmm_spill_sec = None
        swmm_peak_depth = 0.0
        swmm_final_depth = 0.0

        with Simulation(temp_inp_path) as sim:
            u_node_sim = Nodes(sim)[u_node_name]
            start_time = sim.start_time

            for step in sim:
                elapsed_sec = (sim.current_time - start_time).total_seconds()
                d = u_node_sim.depth
                if d > swmm_peak_depth:
                    swmm_peak_depth = d
                # Surcharge overflow occurs when depth exceeds manhole rim (depthM)
                if swmm_spill_sec is None and d >= u_node_depth - 0.02:
                    swmm_spill_sec = elapsed_sec

            swmm_final_depth = u_node_sim.depth

        os.unlink(temp_inp_path)
        # Clean up temp rpt/out files if generated
        for ext in (".rpt", ".out"):
            p_clean = temp_inp_path[:-4] + ext
            if os.path.exists(p_clean):
                try: os.unlink(p_clean)
                except OSError: pass

        # 2. Query Real-Time Model (BlockagePhysics) via Node
        eval_time = 7200 # 2 hours
        js_res = query_node_physics(p_idx, sev, 0.25, eval_time)
        js_depth = js_res["h0"]
        raw_time = js_res["timeToSpillSec"]
        js_spill_sec = raw_time if (raw_time is not None and math.isfinite(raw_time)) else None

        # 3. Calculate Error Percentages
        # Peak depth comparison (capped at chamber depth if spilling)
        swmm_d_eval = min(u_node_depth, swmm_peak_depth)
        js_d_eval = min(u_node_depth, js_depth)

        depth_error_pct = (
            abs(js_d_eval - swmm_d_eval) / max(0.05, swmm_d_eval) * 100.0
        )

        if swmm_spill_sec is not None and js_spill_sec is not None:
            time_error_pct = (
                abs(js_spill_sec - swmm_spill_sec) / swmm_spill_sec * 100.0
            )
            time_display_swmm = f"{swmm_spill_sec / 60.0:.1f} min"
            time_display_js = f"{js_spill_sec / 60.0:.1f} min"
        elif swmm_spill_sec is None and js_spill_sec is None:
            time_error_pct = 0.0
            time_display_swmm = "No spill (>120m)"
            time_display_js = "No spill (>120m)"
        else:
            time_error_pct = 100.0
            time_display_swmm = f"{swmm_spill_sec / 60.0:.1f} min" if swmm_spill_sec else "No spill (>120m)"
            time_display_js = f"{js_spill_sec / 60.0:.1f} min" if js_spill_sec else "No spill (>120m)"

        results.append({
            "id": sc["id"],
            "name": sc["name"],
            "pipe": p_idx,
            "sev": sev,
            "uNode": u_node_name,
            "depthM": u_node_depth,
            "swmm_depth": swmm_d_eval,
            "js_depth": js_d_eval,
            "depth_err_pct": depth_error_pct,
            "swmm_spill": time_display_swmm,
            "js_spill": time_display_js,
            "time_err_pct": time_error_pct,
            "note": sc["note"],
        })

        print(f"  SWMM Depth: {swmm_d_eval:.3f} m | JS Depth: {js_d_eval:.3f} m -> Delta: {depth_error_pct:.1f}%")
        print(f"  SWMM Spill: {time_display_swmm} | JS Spill: {time_display_js} -> Delta: {time_error_pct:.1f}%")

    # Compute Summary Statistics
    depth_errs = [r["depth_err_pct"] for r in results]
    time_errs = [r["time_err_pct"] for r in results]
    depth_errs.sort()
    time_errs.sort()

    median_depth_err = depth_errs[len(depth_errs) // 2]
    median_time_err = time_errs[len(time_errs) // 2]
    mean_depth_err = sum(depth_errs) / len(depth_errs)
    mean_time_err = sum(time_errs) / len(time_errs)

    print("\n" + "=" * 80)
    print("VALIDATION SUMMARY")
    print(f"Median Peak Depth Delta vs EPA SWMM: {median_depth_err:.1f}% (Mean: {mean_depth_err:.1f}%)")
    print(f"Median Spill Timing Delta vs EPA SWMM: {median_time_err:.1f}% (Mean: {mean_time_err:.1f}%)")
    print("=" * 80)

    # Output JSON for publication
    summary = {
        "swmm_version": SWMM_VER,
        "date": datetime.now().strftime("%Y-%m-%d"),
        "median_depth_err": round(median_depth_err, 1),
        "median_time_err": round(median_time_err, 1),
        "mean_depth_err": round(mean_depth_err, 1),
        "mean_time_err": round(mean_time_err, 1),
        "scenarios": results,
    }

    with open("simulation/data/validation_results.json", "w") as f:
        json.dump(summary, f, indent=2)

    return summary

if __name__ == "__main__":
    run_validation()
